import os
import torch
import torchvision.models as models
import torchvision.transforms as transforms
import torch.nn as nn
from PIL import Image
import numpy as np
import cv2
from google import genai
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
from pytorch_grad_cam.utils.image import show_cam_on_image

# Set up runtime engine
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

BINARY_CLASSES = ['fractured', 'not fractured']
TYPE_CLASSES = [
    'Avulsion fracture', 'Comminuted fracture', 'Compression-Crush fracture', 
    'Fracture Dislocation', 'Greenstick fracture', 'Hairline Fracture', 
    'Impacted fracture', 'Intra-articular fracture', 'Longitudinal fracture', 
    'Oblique fracture', 'Pathological fracture', 'Spiral Fracture'
]

# Standard Medical Image Transform Pipeline
infer_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

def load_models(binary_weights_path, type_weights_path):
    """Initializes architectures and attaches your trained weights."""
    # Stage 1: Binary Model (ResNet-50)
    binary_model = models.resnet50()
    binary_model.fc = nn.Linear(binary_model.fc.in_features, 2)
    binary_model.load_state_dict(torch.load(binary_weights_path, map_location=DEVICE))
    binary_model.to(DEVICE).eval()

    # Stage 2: Fracture Type Model (ResNet-50)
    type_model = models.resnet50()
    type_model.fc = nn.Linear(type_model.fc.in_features, 12)
    type_model.load_state_dict(torch.load(type_weights_path, map_location=DEVICE))
    type_model.to(DEVICE).eval()
    
    return binary_model, type_model

def run_ai_pipeline(image_path, binary_model, type_model, output_heatmap_path):
    """Processes X-Ray image through CV models, Grad-CAM, and Gemini Agent."""
    img = Image.open(image_path).convert('RGB')
    input_tensor = infer_transforms(img).unsqueeze(0).to(DEVICE)
    
    # --- Execute PyTorch Computer Vision Pipelines ---
    with torch.no_grad():
        binary_out = binary_model(input_tensor)
        binary_pred = torch.argmax(binary_out, dim=1).item()
        status = BINARY_CLASSES[binary_pred]
        confidence = torch.softmax(binary_out, dim=1)[0][binary_pred].item()
        
        # Safe catch: if clean, exit early without calling Gemini
        if status == 'not fractured':
            return {
                "fracture_detected": False,
                "confidence": confidence,
                "fracture_type": "None",
                "classification_confidence": 0.0,
                "gemini_advice": "No apparent bone fractures detected in this scan. Please consult your physician if physical discomfort persists."
            }
        
        type_out = type_model(input_tensor)
        type_pred = torch.argmax(type_out, dim=1).item()
        predicted_type = TYPE_CLASSES[type_pred]
        type_confidence = torch.softmax(type_out, dim=1)[0][type_pred].item()

    # --- Generate Grad-CAM Explainability Layer ---
    img_resized = img.resize((224, 224))
    rgb_img = np.float32(img_resized) / 255.0
    target_layers = [type_model.layer4[-1]]  # Target the terminal ResNet-50 layer
    
    cam = GradCAM(model=type_model, target_layers=target_layers)
    grayscale_cam = cam(input_tensor=input_tensor, targets=[ClassifierOutputTarget(type_pred)])[0, :]
    visualization = show_cam_on_image(rgb_img, grayscale_cam, use_rgb=True)
    
    # Save visual artifact to disk
    os.makedirs(os.path.dirname(output_heatmap_path), exist_ok=True)
    cv2.imwrite(output_heatmap_path, cv2.cvtColor(visualization * 255, cv2.COLOR_RGB2BGR))
    
    # --- Generate Gemini Agent Medical Guidelines ---
    # The SDK implicitly reads GEMINI_API_KEY from the system environment
    client = genai.Client()
    
    prompt = f"""
    You are an expert AI clinical communicator integrated into MedVision AI.
    Our custom classification model has flagged an X-ray showing a suspected **{predicted_type}**[cite: 1].
    
    Generate a concise, patient-friendly medical advisory report based on standard clinical guidelines using clear Markdown formatting:
    
    ### Clinical Overview
    Provide a clear, plain-English summary explaining what a {predicted_type} is.
    
    ### First Aid & Stabilization
    Provide safe, non-invasive advice for protecting and stabilizing the injury (e.g., elevation, minimizing weight, immobilization constraints) while awaiting professional care.
    
    ### Questions For Your Orthopedist
    Provide 3 distinct, practical questions the patient should ask their consulting specialist regarding this specific condition.
    
    ---
    *Disclaimer: This report is generated by an automated screening mechanism and does not substitute a formal diagnostic evaluation from an emergency professional or radiologist.*
    """
    
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
        )
        gemini_advice = response.text
    except Exception as e:
        gemini_advice = f"AI Advice Engine Unavailable: {str(e)}"
        
    return {
        "fracture_detected": True,
        "confidence": confidence,
        "fracture_type": predicted_type,
        "classification_confidence": type_confidence,
        "gemini_advice": gemini_advice
    }