'use client'

import { motion } from 'motion/react'
import {
  ArrowLeft,
  Printer,
  ShieldCheck,
  FileCheck,
  QrCode,
  ScanLine,
  User,
  Activity,
  AlertTriangle,
  Stethoscope,
  Users
} from 'lucide-react'
import { type AnalysisResult } from '@/types'
import type { View } from '@/components/top-nav'
import { cn } from '@/lib/utils'
import { GlowButton, Button, Alert, Badge } from '@/components/ui'

interface ReportViewProps {
  result: AnalysisResult
  onNavigate: (v: View) => void
}

const toneColor: Record<string, string> = {
  normal: 'text-emerald border-emerald/30 bg-emerald/10',
  attention: 'text-amber border-amber/30 bg-amber/10',
  critical: 'text-critical border-critical/30 bg-critical/10',
}

export function ReportView({ result, onNavigate }: ReportViewProps) {
  const severityTone = result.severityTone || 'normal'

  return (
    <div className="mx-auto max-w-4xl px-5 pt-28 pb-20 print:pt-0 print:pb-0 print:max-w-none print:px-0">
      {/* Top action bar */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-8 flex items-center justify-between print:hidden"
      >
        <Button
          variant="ghost"
          onClick={() => onNavigate('result')}
          iconLeft={<ArrowLeft className="h-4 w-4" />}
          className="rounded-full px-4 py-2 text-sm font-medium text-muted-foreground hover:bg-white/10 hover:text-foreground transition-colors"
        >
          Back to Workstation
        </Button>
        <GlowButton onClick={() => window.print()} iconLeft={<Printer className="h-4 w-4" />}>
          Print / Export PDF
        </GlowButton>
      </motion.div>

      {/* Report Document */}
      <motion.article
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.7 }}
        className="glass-strong relative overflow-hidden rounded-3xl p-8 sm:p-12 border border-white/10 print:border-none print:p-0 print:bg-transparent print:text-black print:shadow-none"
      >
        <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 border-b border-white/10 pb-8 print:border-gray-300">
          <div className="flex items-center gap-3">
            <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan/15 text-cyan border border-cyan/30 print:bg-gray-100 print:text-black print:border-gray-300">
              <ScanLine className="h-6 w-6" />
            </div>
            <div>
              <div className="font-display text-2xl font-bold tracking-tight">
                MedVision<span className="text-cyan print:text-blue-600">AI</span>
              </div>
              <div className="font-mono text-xs text-muted-foreground print:text-gray-600 uppercase tracking-widest">
                Clinical Intelligence Division
              </div>
            </div>
          </div>
          <div className="text-left sm:text-right font-mono text-xs text-muted-foreground print:text-gray-600 space-y-1">
            <div>STUDY ID: <span className="text-foreground print:text-black font-semibold">{result.patientId}</span></div>
            <div>DATE: {result.studyDate}</div>
            <div>STATUS: <span className="text-cyan print:text-blue-600 font-semibold">PRELIMINARY AI REPORT</span></div>
          </div>
        </header>

        <div className="mt-6">
          <Alert variant="warning" title="Clinical Disclaimer Required" className="print:bg-amber-50 print:border-amber-200 print:text-amber-900">
            This report contains automated AI findings generated by MedVision AI. These results are preliminary investigatory insights and must be independently verified by a licensed radiologist or orthopedic specialist.
          </Alert>
        </div>

        <section className="mt-8 grid gap-6 sm:grid-cols-2 rounded-2xl bg-white/5 p-6 border border-white/5 print:bg-gray-50 print:border-gray-200">
          <div>
            <h3 className="font-mono text-xs uppercase tracking-widest text-cyan print:text-blue-600 mb-3 flex items-center gap-1.5">
              <User className="h-3.5 w-3.5" /> Patient Demographics
            </h3>
            <dl className="grid grid-cols-2 gap-y-2 text-sm">
              <dt className="text-muted-foreground print:text-gray-600">Patient ID:</dt>
              <dd className="font-mono font-medium">{result.patientId}</dd>
              <dt className="text-muted-foreground print:text-gray-600">Age / Sex:</dt>
              <dd className="font-medium">{result.age} / {result.sex}</dd>
            </dl>
          </div>
          <div>
            <h3 className="font-mono text-xs uppercase tracking-widest text-cyan print:text-blue-600 mb-3 flex items-center gap-1.5">
              <Activity className="h-3.5 w-3.5" /> Study Metadata
            </h3>
            <dl className="grid grid-cols-2 gap-y-2 text-sm">
              <dt className="text-muted-foreground print:text-gray-600">Modality:</dt>
              <dd className="font-medium">{result.studyType}</dd>
              <dt className="text-muted-foreground print:text-gray-600">AI Model:</dt>
              <dd className="font-mono text-xs">ResNet-50 v1.0</dd>
              <dt className="text-muted-foreground print:text-gray-600">Overall Confidence:</dt>
              <dd className="font-mono text-xs text-emerald print:text-green-700">{result.overallConfidence.toFixed(1)}%</dd>
            </dl>
          </div>
        </section>

        <section className="mt-8 rounded-2xl border border-cyan/30 bg-cyan/5 p-6 print:bg-blue-50 print:border-blue-200">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <span className="font-mono text-xs uppercase tracking-widest text-cyan print:text-blue-600 font-semibold">Primary Clinical Impression</span>
              <h2 className="mt-1 font-display text-2xl font-bold tracking-tight text-foreground print:text-black">
                {result.primaryImpression}
              </h2>
            </div>
            <div className="flex items-center gap-3">
              <Badge
                tone={severityTone as any}
                className={cn('px-4 py-1.5 text-xs font-semibold uppercase tracking-wider border', toneColor[severityTone])}
              >
                {result.severity}
              </Badge>
            </div>
          </div>
        </section>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
          <section>
            <h3 className="font-display text-lg font-semibold mb-4 flex items-center gap-2">
              <FileCheck className="h-5 w-5 text-cyan print:text-blue-600" />
              Clinical Summary
            </h3>
            <div className="text-sm text-muted-foreground print:text-gray-700 space-y-4 bg-white/5 p-5 rounded-xl border border-white/10 print:bg-gray-50 print:border-gray-200">
              <p><strong>Findings:</strong> {result.summary}</p>
            </div>
          </section>

          <section>
            <h3 className="font-display text-lg font-semibold mb-4 flex items-center gap-2">
              <Stethoscope className="h-5 w-5 text-cyan print:text-blue-600" />
              Doctor Guidance
            </h3>
            <div className="text-sm text-muted-foreground print:text-gray-700 space-y-4 bg-white/5 p-5 rounded-xl border border-white/10 print:bg-gray-50 print:border-gray-200">
              <p><strong>Recommended Imaging:</strong> {result.doctorGuidance?.recommended_imaging || 'N/A'}</p>
              <p><strong>Followup:</strong> {result.doctorGuidance?.suggested_followup || 'N/A'}</p>
              <p><strong>Differential Considerations:</strong> {result.doctorGuidance?.differential_considerations || 'N/A'}</p>
              <p><strong>Notes:</strong> {result.doctorGuidance?.important_notes || 'N/A'}</p>
            </div>
          </section>
        </div>

        {result.medicalDebate && result.medicalDebate.length > 0 && (
          <section className="mt-8">
            <h3 className="font-display text-lg font-semibold mb-4 flex items-center gap-2">
              <Users className="h-5 w-5 text-cyan print:text-blue-600" />
              Medical Specialist Debate
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {result.medicalDebate.map((op, idx) => (
                <div key={idx} className="bg-white/5 p-4 rounded-xl border border-white/10 print:bg-gray-50 print:border-gray-200 text-sm">
                  <h4 className="font-semibold text-cyan mb-2">{op.role} ({(op.confidence * 100).toFixed(0)}%)</h4>
                  <p className="text-muted-foreground mb-3">{op.summary}</p>
                  <div className="space-y-1">
                    <strong>Concerns:</strong>
                    <ul className="list-disc pl-4 text-muted-foreground">
                      {op.concerns.map((c, i) => <li key={i}>{c}</li>)}
                    </ul>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {result.consensus && (
          <section className="mt-8 rounded-2xl bg-cyan/10 p-6 border border-cyan/20 print:bg-blue-50 print:border-blue-200">
            <h3 className="font-mono text-xs uppercase tracking-widest text-cyan print:text-blue-600 mb-3 font-semibold">
              Tumor Board Consensus
            </h3>
            <p className="text-sm text-muted-foreground mb-4">{result.consensus.summary}</p>
            <div className="text-sm text-muted-foreground">
              <p><strong>Agreement:</strong> {result.consensus.agreement}</p>
              <p><strong>Remaining Uncertainty:</strong> {result.consensus.remaining_uncertainty}</p>
              <p className="mt-3 font-semibold text-foreground">Next Step: {result.consensus.recommended_next_step}</p>
            </div>
          </section>
        )}

        <footer className="mt-12 border-t border-white/10 pt-8 print:border-gray-300">
          <div className="grid gap-6 sm:grid-cols-3 items-center">
            <div className="space-y-1 text-center sm:text-left">
              <div className="font-mono text-xs uppercase tracking-widest text-muted-foreground print:text-gray-600">Model Verification</div>
              <div className="flex items-center gap-2 text-xs font-mono text-emerald print:text-green-700">
                <ShieldCheck className="h-4 w-4" />
                Verified Signature
              </div>
            </div>
            <div className="flex justify-end items-center gap-3 col-span-2">
              <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-white/10 border border-white/15 print:bg-gray-100 print:border-gray-300">
                <QrCode className="h-8 w-8 text-cyan print:text-black" />
              </div>
            </div>
          </div>
          <div className="mt-8 text-center font-mono text-[10px] text-muted-foreground/50 print:text-gray-500">
            MedVision AI Platform v1.0 · Generated {new Date().toISOString()} · Page 1 of 1 · Confidential Medical Document
          </div>
        </footer>
      </motion.article>
    </div>
  )
}
